MNT: Re-rendered with conda-smithy 3.1.12 and pinning 2018.10.01

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -7,33 +7,57 @@ os: osx
 osx_image: xcode6.4
 
 env:
+  matrix:
+    - CONFIG=osx_
+
   global:
     # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
     - secure: "hrRJ2Jh4NrjQsE/YSPknOxGPpvRJZWSCYt72hWuhk/9FcW7jtMjwsL/PIXBdMgpZPdNv0ZBkCHSPTCL14SSHS2sdRsBI8f/N4inAsJRXNK0ICNYWX6xG5GxUdTy5n03QJrzQ+81dhNmBSWHZNVdbxf7pvTCxtzCd0EV2m81wrKWzrVbFwfkRPYV6VP1ib0vmRLb1jCOgMl9imClsWPTDsaXTXbcHWinZhuW6Rz08QV25IiKqf2kGvoNtgkhoCR0jxV1PaKuwdFaqX9prCRCwZgKGQ1ga6dr27TDOoYf4yRRPA+b6Kmw9jWeiq6P69KmX6YNKyGZQDb+1sireCWCKo+MHY3OprTaxyDEIJq8hRsqHaIe2ii8hYUKdArMnBGR7XsMNC+oSqBlnX0ulrN6r5jQ6VDyQHaZb0j3AvwN6ttgO2CfvEzbIgTg74Fj9uZ1H5cOI0DB0BZ0z4PY5tevVtddnOGwgRzDjOG+5Rmxu0QoVkP9iZfg2Mp4C6xUFa9A2HIEHdmwEYdtRF1ULbgoImfCdoq6eWCGBTk2lhiuYoa1XAz9SosI4GqyfYyPpRvb9KhJj8jGwBi9AwHlta3cvvXuyl5/UrbJgL78eW6T6gTTrMa9D2rruuNBvxaQFhDYwvoaPTBMYVHGt/PLXCuwJFqnv5sBUnNB3hGHOqt6zCA8="
 
 
 before_install:
+    # Fast finish the PR.
+    - |
+      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
+          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1
+
     # Remove homebrew.
-    - brew remove --force --ignore-dependencies $(brew list)
-    - brew cleanup -s
-    - rm -rf $(brew --cache)
+    - |
+      echo ""
+      echo "Removing homebrew from Travis CI to avoid conflicts."
+      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
+      chmod +x ~/uninstall_homebrew
+      ~/uninstall_homebrew -fq
+      rm ~/uninstall_homebrew
+
 
 install:
+    # Install Miniconda.
     - |
+      echo ""
+      echo "Installing a fresh version of Miniconda."
       MINICONDA_URL="https://repo.continuum.io/miniconda"
       MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
       curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
       bash $MINICONDA_FILE -b
 
+    # Configure conda.
+    - |
+      echo ""
+      echo "Configuring conda."
       source /Users/travis/miniconda3/bin/activate root
-      conda config --remove channels defaults
-      conda config --add channels defaults
-      conda config --add channels conda-forge
-      conda config --set show_channel_urls true
-      conda install --yes --quiet conda-forge-build-setup
+
+      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
+      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml
+
       source run_conda_forge_build_setup
 
-script:
-  - conda build ./recipe
+    # compiler cleanup
+    - |
+      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml
 
-  - upload_or_check_non_existence ./recipe conda-forge --channel=main
+script:
+  # generate the build number clobber
+  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
+  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
+  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
